ENV:
  device: GPU
  output_dir: ./output_seg/
  save: True
  visualize: True

PipeLine:
  - BaseSegmentation:
      config_path: ./configs/seg/ocrnet/ocrnet_hrnetw18_defect_1024x512_160k.yml 
      model_path: ./output/mt_seg/best_model/model.pdparams
      aug_pred : False
  - PostProcess:
      - JudgeByArea:
          area_thresh: 0
