ENV:
  device: GPU
  output_dir: ./tmp/
  save: True
  visualize: False

PipeLine:
  - BaseSegmentation:
      config_path: ./configs/seg/ocrnet/ocrnet_hrnetw18_ksdd2.yml 
      model_path: ./output/ksdd2/best_model/model.pdparams
      aug_pred : False
  - PostProcess:
      - JudgeByArea:
          area_thresh: 10
