ENV:
  device: GPU
  output: ./tmp/
  save: True
  visualize: True

PipeLine:
  - BaseSegmentation:
      config_path: ./configs/seg/ocrnet/ocrnet_hrnetw18_ksdd2.yml 
      model_path: ./output/ksdd2/iter_160000/model.pdparams
      aug_pred : False
      visualize: False
  - PostProcess:
      - JudgeByArea:
          area_thresh: 100
