_BASE_: [
  '../datasets/defect_detection.yml',
  './_base_/faster_rcnn_hrnetv2p_w18.yml',
  '../faster_rcnn/_base_/optimizer_1x.yml',
  './_base_/faster_fpn_defect_reader.yml',
  '../runtime.yml',
]

weights: output/faster_rcnn_hrnetv2p_w18_1x_coco/model_final
epoch: 12

LearningRate:
  base_lr: 0.02
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [8, 11]
  - !LinearWarmup
    start_factor: 0.1
    steps: 1000

TrainReader:
  batch_size: 16
