_base_: '../_base_/cityscapes.yml'

batch_size: 2
iters: 160000

train_dataset:
  type: Dataset
  dataset_root: dataset/kolektor2/ROI/
  num_classes: 2
  mode: train
  train_path: dataset/kolektor2/ROI/train.txt
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.5
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [60, 60]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.5
      contrast_range: 0.5
      saturation_range: 0.5
    - type: Normalize

val_dataset:
  type: Dataset
  dataset_root: dataset/kolektor2/ROI/
  num_classes: 2
  mode: val
  val_path: dataset/kolektor2/ROI/val.txt
  transforms:
    - type: Normalize

model:
  type: OCRNet
  backbone:
    type: HRNet_W18
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w18_ssld.tar.gz
  num_classes: 2
  backbone_indices: [0]

optimizer:
  type: sgd

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  power: 0.9


loss:
  types:
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
  coef: [1, 0.4]
